# run this json-server command below first to get localhost:3000 running
# json-server --watch test.json 

# GET http://localhost:3000/users

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "first_name": "Murali",
    "last_name": "Koujala",
    "email": "koujala@gmail.com"
}